### ISSUE TITLE
Final Tasks

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [Samantha-Mcguigan/newsAnalysis#18]
- [x] @ajnewton1 moving the drop down menus, page titles, and other website navigation. Make the News Analysis title be its own link to "home". Add link to the GitHub repo somewhere!

- [x] @ajnewton1 add the search feature (with code) so it's active on the menu bar.

- [x] @jonhoranic search.php: add `<div>` elements and other features for display of pages. 

- [x] @jonhoranic **spelling/grammar(!)**, xml editing (look for files missing `<hyperlink>` elements and look for weird tagging issues

- [x] @Samantha-Mcguigan  finish write ups for network graphs, fix how SVG elements are sitting on the website, adding photos to the about the team page, add links to articles and new header to source pages

- [x] **(you should probably do this together)**: Reflection and conclusion on the WHOLE project (what major things did you learn?) Feature this on the home page of the website.

**Comment by ebeshero** [comment]
Here are a couple of short posts about the problem of drop-down menus for site navigation:

https://www.rocketspark.com/blog/drop-down-menus-5-reasons-we-dont-use-them-and-3-tips-what-do-instead/

https://www.joedolson.com/2013/07/designing-accessible-navigation/

The second article discusses accessible design features, and while it offers some recommended ways to code pages, the real takeaway here is awareness of what can go wrong, and designing so that the CSS and JavaScript aren't essential to navigate around the site if these scripts ever don't work.  

 (I'm redesigning some of my own sites to get rid of my old drop-down menus--so all of this is in-process for me, too.)

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 
Are one of you working on the site right now?

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan I will not be working on anything until tomorrow after my morning final, as I am under a severe time crunch finishing these papers for turn in (tonight and tomorrow).

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic I was just trying to work on some things and the header was changed and it wasn't me who did it.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan I noticed that there were some changes made, @ajnewton1 has done some of that work so far but I am unsure if he has fully finished that yet. All that would require is copy/paste work for pages that do not have it yet. If there are problems occurring because of it note what they are here so we do not overwrite each others edits.

**Comment by Samantha-Mcguigan** [comment]
@ebeshero @RJP43 I'm having a problem putting the links for the articles on their corresponding pages. I have this in the html document:
```
            <ul>
                <li><a href="http://www.npr.org/2016/11/09/500716650/donald-trump-clinches-the-presidency-in-major-upset">Election Results</a></li>
            </ul>
```
the list is inside a `div class="text"` as well. And then we have this in the CSS:

```
a:link{
    text-decoration: none;
    color: #FFFAFA ;
}
a:visited{
    text-decoration: none;
    color: #FFFAFA;
}
```
And when I go to the website the link is there but it must be white because I can't see it?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan @ajnewton1 @jonhoranic Just a heads up: Something just recently changed rather drastically in your site's CSS.  

I'd encourage you to test changes locally before rewriting each other's work on the website.  It looks like the last push to the repo was mine from two days ago, so presumably you can retrieve the CSS as it was. (You can always retrieve it from the commit history of the repo on the web, too.)  Sam, you mentioned the problem of hyperlinks coming out in white on white background. That was set for the links on the nav bar, but you want to be putting a class or something on the links that appear in the body of the document. 

Alternatively, you could rewrite the CSS so that links in the navbar have a special class="nav", and style those only to be white, and then style the other links differently. But please announce and coordinate with each other on this.

**Comment by Samantha-Mcguigan** [comment]
@ajnewton1 @jonhoranic @ebeshero  I added to the CSS to create clickable links on the source pages (NPR.html) the menu at the top has also been changed but I don't think that was from me

**Comment by Samantha-Mcguigan** [comment]
I went back and copied what was in Git Hub to the CSS and uploaded it to the site and the menu bar is still the same without the changes I made so its not from me

**Comment by ebeshero** [comment]
I wonder if someone changed the SSI file: menu.html?

**Comment by Samantha-Mcguigan** [comment]
Maybe @ajnewton1 is working on it?

**Comment by ebeshero** [comment]
I'll check the last time it was edited on the server (we should be able to see that...)

**Comment by ebeshero** [comment]
Nope--the menu.html file remains as it was from April 24. I'll take a closer look to compare the file on the web server with the files we have on GitHub.

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I copy and pasted the CSS on GitHub on to my local computer and uploaded it to the site and it didn't change the menu which is strange because when we had that same CSS on the site 2 days ago it looked different. I'm not sure what the problem is because the it was fine before I started working a few hours ago..

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I'm inspecting the repo and the state of the web files--I bet there's an issue with Aaron's working over in his new branch of the repo--I think the master branch is missing the files as he worked on them. I'm taking a look over in his branch and comparing with the code we see on the web server right now.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan OHHH! I think I know what happened. It's not your fault (don't worry!)--I'll confirm in a moment.  I think you started working with the CSS in your master branch, but Aaron has some special styling over on his branch, which he didn't merge with the master branch.

That means, *your* CSS file from the master branch is missing the CSS that controls the buttons on the newly styled header. Look at Aaron's CSS here:
https://github.com/Samantha-Mcguigan/newsAnalysis/blob/ajn54/Website/style.css

**Comment by ebeshero** [comment]
@ajnewton1 and @Samantha-Mcguigan We need to merge your changes to the CSS together on the master branch. I think I can do this by issuing a pull request and asking GitHub to help with the merge... (Presumably Aaron's in a final or something...! But I think we can fix this...) I just taught Aaron how to work in his own branch at your project meeting on Monday, and I think he just forgot to do the pull request (or figured no one else was going to make changes to the CSS, etc).

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I'm willing to copy and paste what is on Aaron's CSS into the CSS I have on my computer and just add my changes onto that. Its only a few styling things for the links if that would be easier.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan That's effectively doing the merge by hand, and we may need to do that anyway, but let me take a look and compare the branch content first. I think we liked Aaron's changes, right? So maybe we should just commit them to the master branch anyway so we don't risk overwriting the website content again on other files!

**Comment by Samantha-Mcguigan** [comment]
@ebeshero Sounds good to me! I will continue working on adding the links in my local branch in the meantime. By the way @jonhoranic while I'm doing this I'm able to see where we are missing hyperlinks in the XML documents so I will fix that while I'm there so you don't have to worry about it.

**Comment by dotfig** [comment]
I was working on the website a few days ago. I think we should meet sometime tomorrow to get everything figured out

**Comment by ebeshero** [comment]
@ajnewton1 @Samantha-Mcguigan I think I've resolved the conflict and made it safe to edit the web files again... Everyone do a Git Pull!

**Comment by ebeshero** [comment]
@ajnewton1 Make sure you're standing on the master branch when you pull.

**Comment by dotfig** [comment]
Did someone mess with the website?

**Comment by ebeshero** [comment]
@ajnewton1 We're fixing it!

**Comment by ebeshero** [comment]
@ajnewton1 There was an old copy of the CSS on the master branch... the others didn't have access to your CSS, and made a new edit to style links in the bodies of the HTML file. I'm about to replace what's on the web with your CSS. @Samantha-Mcguigan Check the style.css that you just pulled in from the "master" branch--I don't think you committed your changes to the master branch, did you?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan @ajnewton1 I'm going to put the CSS that I just pulled from Aaron's branch back up on the website. Sam, I think it's going to need your edits, still, so your links will probably go back to being white again.

**Comment by ebeshero** [comment]
And go take a look at the website again! (whew!) Menu restored. :-)

**Comment by ebeshero** [comment]
@Samantha-Mcguigan Add your edits to this revised CSS currently on your master branch of GitHub, and then push them back.

@ajnewton1 As you're working in your own separate "ajn" branch, you just need to send pull requests over the master branch so the others have access to your files. It's important so someone doesn't accidentally overwrite your updates to the website.

**Comment by ebeshero** [comment]
**Rule of thumb** for all of you: once it's worthy to be posted on the website, it MUST be committed to the master branch of your project repo, so the entire team is using up-to-date files.

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I just pulled and I'm getting an error that my local changes will be overwritten by merge. Should I push my changes first?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan That's okay, and actually **good** because it means GitHub is recognizing your changes. Go ahead and **commit** your changes first. Then do `git status` and report what you see.

**Comment by Samantha-Mcguigan** [comment]
Your branch is behind 'origin/master' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

**Comment by ebeshero** [comment]
@Samantha-Mcguigan OK--good! Go ahead and `git pull`.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan everything okay? Or merge conflict?

**Comment by Samantha-Mcguigan** [comment]
It saying the files will be overwritten by merge

**Comment by Samantha-Mcguigan** [comment]
Its telling me to commit or stash them

**Comment by ebeshero** [comment]
Hmmm. Did you make lots of changes you won't remember how to do again, or do you think it's best to start over with fresh files?

**Comment by Samantha-Mcguigan** [comment]
No I can start over its no big deal

**Comment by ebeshero** [comment]
OK...let's give `git stash` a try...

**Comment by ebeshero** [comment]
...if nothing happens, type `git status`.

**Comment by Samantha-Mcguigan** [comment]
Saved working directory and index state WIP on master: 6a17908 making spot repair to menu.html so it fits into the whole as well-formed HTML
HEAD is now at 6a17908 making spot repair to menu.html so it fits into the whole as well-formed HTML

**Comment by ebeshero** [comment]
YAY!

**Comment by ebeshero** [comment]
Do a `git pull` now

**Comment by Samantha-Mcguigan** [comment]
whoop!

**Comment by ebeshero** [comment]
All in?

**Comment by Samantha-Mcguigan** [comment]
Yep! Am good to start working again?

**Comment by ebeshero** [comment]
@ajnewton1 @Samantha-Mcguigan I'm going to check to make sure the pages are well-formed in HTML: taking a peek in the w3c Validator. PAUSE a moment while I do this.

**Comment by ebeshero** [comment]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fnewsanalysis.newtfire.org%2F

Nothing serious, but you guys do have the xml line at the top. It's not a HUGE deal, but @ajnewton1 some of the pages might not be showing the search icon (need the UTF8 signal). 

@Samantha-Mcguigan Yes, I think you can go ahead and work in your changes. And push to the master branch when you're ready. 

@ajnewton1  I'd maybe be sure you're working in the master branch at this point, or pull in Sam's changes before you begin anything...(or start a new branch after Sam's done updating...)

**Comment by Samantha-Mcguigan** [comment]
@ebeshero @jonhoranic @ajnewton1 On some of the pages text and images are being cut off at the bottom by the blue bar and I'm not sure why. Any ideas?

**Comment by dotfig** [comment]
@Samantha-Mcguigan Put a few ``</br>`` right before the blue bar.

**Comment by Samantha-Mcguigan** [comment]
Nevermind @ajnewton1 in the CSS the bottom was set as fixed instead of relative!

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 Would you two want to put conclusions under the Methodology page or create a new page? I was thinking we could create a new issue and edit it together or if you want to meet, I can do between 3 and 6.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan I think removing that bottom paragraph at the bottom of the homepage (or moving it to methodology) and putting our conclusions in short there would tie up everything there on the homepage at a glance, then the reader could click around to see for themselves.

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 okay, Im going to go ahead and move that.

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton so are we meeting today or just creating a new issue for conclusions?

**Comment by dotfig** [comment]
@Samantha-Mcguigan @jonhoranic I can meet today. I have a final at 3:15 so hopefully I will be out by 4. But if no one is around then we can just make an issue

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 I am unfortunately sick as a dog, a recent flare up this morning prevented me from making it to the college. I am doing what I can, I can work from an issues board if need be, let me know. I will be working on the write up content soon, let me know if there are any descriptions you think we should add.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 I am almost done with the last few edits of the site info, the files as pushed can go right up on the site but please look them over just to make sure we agree on everything written.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan @ajnewton1 All spelling/grammar is checked, I am moving on to link problems for the moment. Let me know if there is anything else I am missing.

EDIT: Not seeing any issues with the links on my end, each one in the hyperlink element works.

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 are either one of you going to add to the conclusions paragraph? If not I'm just going to put it up as is. @jonhoranic are you going to turn the project in?

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 I went ahead and pushed the conclusions to the index page, feel free to change it. @jonhoranic since you are our fearless leader I'm going to leave it to you to create the final issue letting Dr. B and Becca know our site is ready for grading.

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan Sorry for not seeing this last night, I am putting up an issue now. I will ping @ajnewton1 and everyone else from it.
