### ISSUE TITLE
XML Markup Questions

### ISSUE THREAD

**Issue by Samantha-Mcguigan** [Samantha-Mcguigan/newsAnalysis#5]
@jonhoranic @ajnewton1 
I was wondering if you guys were saving articles from websites by saving the page as an html document and then changing it to save it as an XML document or if you were just copy and pasting it from the site into a new xml document on oxygen?

**Comment by Samantha-Mcguigan** [comment]
Also, I was going to nest `<quote>` tags inside `<p>` since all quotes will be their own paragraphs if that sounds good to everyone.

Should links that are part of their own paragraph also have `<p> `tags?

In the first article I am coding there are sub headings within the article body so I am going to code them as `<subHead>` and put them inside `<p>` tags

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan GitHub has been having hiccups for me, I apologize for not seeing your earlier post! Anyway:

1. I personally do not save the articles, they can a bit messy that way. Copy and pasting helps get the main text, which is what we are focusing on, however if you find it easier do what works best.
2. The quote thing sounds good to me, I have been doing that too for paragraphs that are really just a "block quote" in line with the text.
3. I think that subheading idea works better than what I have currently, I will go back in and address that. You can make edits to that "cheat sheet"/referance thing I did. Which reminds me, @ajnewton1 that might help with building the schema (sorry that I forgot to mention that during our class!).

Any other things you find/edit, let us know and just make the executive decision.

**Comment by Samantha-Mcguigan** [comment]
I was thinking we could save articles like by putting the topic first, then the what site it comes from so:

electionResults_CNN.xml
electionResults_FOX.xml

etc...

we can also add the date the article was published if you want. What do we think?

**Comment by Samantha-Mcguigan** [comment]
Sorry, last thing for tonight, under one of the videos on the site there is this description

Donald Trump: Hillary Clinton called to congratulate us 00:48

I had it just tagged as a paragraph but I think I might just delete it since it doesn't really help with our research?

**Comment by Samantha-Mcguigan** [comment]
@jonhoranic @ajnewton1 @ebeshero @RJP43 
Okay, I lied, I have one more question, there is some emotional language in the articles that are neither adverbs or adjectives and I think we would be missing out on some good results if we didn't code those as well so I was thinking we either code them the same as we are coding the adjectives and adverbs so:

`<verb type="emo"> `

or we could change the attribute to express the type of language instead, that way all the emotional language will have the same tag so:

```
<emo type="verb">
<emo type="adv">
<emo type="adj">
etc.
```

I think the second one might be better for our purposes but I want to know what you all think before I continue coding.

Sorry for all the questions but I wanted to get my thought process out and make sure we are all on the same page now rather than later!

**Comment by dotfig** [comment]
@Samantha-Mcguigan for the video, you might want to just tag it with ````<media/>```` but make sure it is out of the ````<p></p>```` tags

**Comment by dotfig** [comment]
@Samantha-Mcguigan @jonhoranic I have been merely basing the Relax-NG on the examples that @jonhoranic gave us and also the markup. I will post it as soon as I get done just so we have enough time to make adjustments to it.

**Comment by dotfig** [comment]
@Samantha-Mcguigan it doesn't matter to me. I am assuming you are doing the second one though

**Comment by jonhoranic** [comment]
@Samantha-Mcguigan 
1. Sounds good! Just name them and then push them when you are ready so we can use them as the file naming standard.
2. The video tags should be excluded really, if you want to nest them in a comment tag or just make a note that one existed there that would be fine.
3. Having them all be the same element works better, that way we can mark them much faster then all we would need to do is double check the parts of speech they are as we go. Good idea

**Comment by jonhoranic** [comment]
@ajnewton1 With what @Samantha-Mcguigan is doing with the tags, you can write a rule for the ````<emo>```` element that if it does not have a proper type attribute from the three we have that would be a good flag for us to make corrections.

**Comment by dotfig** [comment]
The Relax-NG is in the articleRef folder @jonhoranic @Samantha-Mcguigan. I tested it on the Women's March and Election example and seemed to be alright except for a few minor things. In the ````date```` element, I used ````xsd:date```` which means that the format should be ````YYYY-MM-DD```` and in the ````<time>```` element I used ````xsd:time```` which means that the format should be ````hh:mm:ss````. If we don't want a specific format I can always just put it as plain text.

In the ````<credit>```` element, there should be either an ````<author>```` or ````<editor>```` element to show who wrote it. 

I wrote everything out in the Relax-NG as comments so hopefully it'll be clear. The only thing that @Samantha-Mcguigan might want to add would be the ````<subHeader>```` element. I wasn't sure what was going on with that. Any questions feel free to tag me in a comment.

**Comment by jonhoranic** [comment]
@ajnewton1 Looks good to me, at least from the Github mobile interface. When I return home I'll look at it through Oxygen and run it a few time. Keep up the good work! 

Are you continuing now with mark up of articles? Let us know if you need any assistance.

**Comment by dotfig** [comment]
Yes I should be good with the articles. Look at the website and let me know how you guys like it. http://newsanalysis.newtfire.org/index.html

**Comment by ebeshero** [comment]
@ajnewton1 I think the website looks sharp! I especially like how you linked from the news logos: the images are functional to tell us exactly what news outlets you're tracking. 

 Here are some things to correct and/or think about:
*  The menu is missing apostrophes on "Women's March" and "Trump's Tax Release". 
* As your project starts adding visualizations and analysis do you think you'll want a page that summarizes your findings across all the topics (as well as breaking them down individually)? 
* Do you think you'll be covering other topics besides these three? In case you (or others in future) want to expand the site, you might want just a single main menu item for "News Topics", that leads to a page with an *internal* menu listing all the topics together and linking out to what you're doing with each one. 
* Dates are missing here: Two or three years from now, people won't remember some of these events or when they happened. Also, more importantly, you want to be clear about the chronological time you're working with on each issue: so for each issue you'd say something like: articles published between 8 November 2016 and [?? ???? 201?] You should add that info to each issue, (and plan to update it as you add more material). 
 (In addition, I imagine you'll want to link directly to each article you marked up (directly to its source?) Just thinking ahead about how this is likely to develop.)

**Comment by dotfig** [comment]
@jonhoranic @Samantha-Mcguigan Are you guys able to help me out with marking up my Trumps Taxes files? I pushed them to the repo. The only thing that I need help with are the ````emo```` tags. I am not confident with my knowledge of adverbs, verbs, adjectives, etc.

**Comment by jonhoranic** [comment]
@ajnewton1 @Samantha-Mcguigan I am starting to see that if we were to work on tagging the emotional elements for each file, one by one, we will be held up for a considerable length of time on each. Perhaps it would be best if we could get our batches of files "structurally" coded first, then go back in and start tagging the emotional bits. I am testing some possible solutions (some web programs and such) that will be a faster way to find them. Of course, it will not be perfect, so it will require a set of human eyes to check for errors. I will let you guys know if I find something viable. 

What do you two think about just pushing structural mark up for now?

**Comment by dotfig** [comment]
Yea I agree @jonhoranic. Would you say that we should still complete the ````<a href="">```` tags and tags that involve anything with quotes? ````<q>```` and ````<quote>````

**Comment by jonhoranic** [comment]
@ajnewton1 I think that would be worth while, those will take less time and I think fit into the class of structure, if necessary, mark all the quotes in the shorter ````<q>```` tag which I believe covers ALL quotes, we can go back and add to them if they are really ````<quote>```` which I believe are only SPECIFIC instances.

I could also be **horribly** wrong here but if that helps lighten the load for now. If we do? We should note that we are doing it so we can be ready to fix them when we close read our files again.

EDIT: In my head it is the "all bananas are plantains, but not all plantains are bananas" situation for those quote tags. But again I can be proven wrong here! So proceed with mild caution.

**Comment by dotfig** [comment]
@jonhoranic I think we discussed that ````<q>```` is only used for random words/phrases that were enclosed with quotation marks and ````<quote>```` is only used for when someone is actually speaking. Trump's Taxes are pushed into the repo and the website is as far as it can be I think for now. All of the website files are in the repo as well so fell free to add or take away anything that you don't think should be there.

**Comment by jonhoranic** [comment]
@ajnewton1 Sounds about right, thank you for the reminder. I will be ready to get the women's march ones up within the hour.

**Comment by dotfig** [comment]
@Samantha-Mcguigan I incorporated the ````<subHeader>```` into the Relax-NG but I didn't make it go inside the ````<p>```` tag. It just stands by itself inside the ````<body>```` tag
