### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by RJP43** [Samantha-Mcguigan/newsAnalysis#9]
Pitt-Oakland and others comment on this issue with your comments on today's presentation.

**Comment by RJP43** [comment]
A comment/suggestion I have on this project in regards to the bar graph analysis would be to organize the x-axis by news source and perhaps use javaScript to toggle between news topics. I think this setup would be more indicative of what the project is analyzing as in the language difference between news sources not between news topics.

I like the idea of having different bar graphs for each demographic mark up as in gender and political affiliation.

**Comment by emz15** [comment]
Hi guys,
I really like the topic of your project here, and I think it’s particularly important given the time period we’re in right now with our current administration. But I do have a couple questions about your project. 
I like the diversity in outlets you chose to analyze for this project, but how did you decide on these outlets? I understand you were looking for sources with a variety of leans, but why did you chose different types of media, like television and radio, for example? Has this skewed your results? If you are only looking at text articles for your data, why didn’t you chose legacy news sources like The New York Times or the Wall Street Journal? What are some problems you can predict might happen with the data you chose? Also, I see you chose Fox, which is notorious for its far-right tendencies. Why didn’t you also chose something like MSNBC, which is known for its left-leaning tendencies?
It might also be worth looking into the gender of the people who are covering the topics you discussed on your analysis page. If a news anchor or writer is a man, it’s more likely that he’ll pick men to quote in his story – on the other hand, if the reporter is a woman, it’s more likely that she’ll pick other women, or more diverse sources. So some of the bias you’re encountering might be based on the individual journalists’ leanings, which means that some of this bias might not be as institutionally rooted in each of the news outlets.
What information are you planning on including in the outlet tabs on your website? Right now, I see that you have informational blurbs for each of the outlets, but I’m curious what you’re planning on bulleting beneath those. Are you planning on including graphs in these sections or just on the analysis page? Are you planning on hyperlinking the articles you analyzed on these outlet tabs?
Overall, your project is super pertinent and I’m interested to see where you’ll take it!
--Elaina (Immigration Station)

**Comment by RJP43** [comment]
Also reference Issues #10 and #11
